const fs = require("fs");
const path = require("path");

const outputToFile = requireSrc("outputToFile");

const FILENAME = path.resolve(process.cwd(), "test/tmp.ts");
const CONTENT = "_CONTENT_";

describe("outputToFile", function(){

	function reset(){
		try {
			fs.unlinkSync(FILENAME);
		}catch(e){
			// Might not exist
		}
	}

	beforeEach(reset);
	afterEach(reset);

	it("Is a function", function(){
		assert.isFunction(outputToFile);
	});

	it("Can output file with a comment with the date", function() {
		outputToFile(FILENAME, CONTENT);

		const provided = fs.readFileSync(FILENAME).toString();

		const REGEXP = /\/\/ Generated by typed-directory on \d{2}\/\d{2}\/\d{4} \d{2}:\d{2}:\d{2}\n_CONTENT/g;
		assert.match(provided, REGEXP);
	});
});