// Generated by typed-directory on 01/28/2018 16:44:47
import Animal from "../animals/Animal";

import _domestic_Cat from "../animals/content/domestic/Cat";
import _domestic_Dog from "../animals/content/domestic/Dog";
import _zoo_Lion from "../animals/content/zoo/Lion";

const domestic_Cat:Animal = _domestic_Cat;
const domestic_Dog:Animal = _domestic_Dog;
const zoo_Lion:Animal = _zoo_Lion;

export default {
	"domestic": {
		"Cat": domestic_Cat,
		"Dog": domestic_Dog
	},
	"zoo": {
		"Lion": zoo_Lion
	}
};