const fs = require("fs");
const mkdirp = require("mkdirp");
const path = require("path");

module.exports = function(filename, content){
	// Make dir if doesn't exist
	const parsed = path.parse(filename);
	mkdirp.sync(parsed.dir);

	// Add header with date
	const generationComment = `// Generated by typed-directory on ${datetime()}`;
	content = generationComment + "\n" + content;

	// Output file
	fs.writeFileSync(filename, content);

	// Make file readonly
	fs.chmodSync(filename, 0o444);
}

function datetime(){
	const d = new Date();

	return (
		("00" + (d.getMonth() + 1)).slice(-2) + "/" + 
	    ("00" + d.getDate()).slice(-2) + "/" + 
	    d.getFullYear() + " " + 
	    ("00" + d.getHours()).slice(-2) + ":" + 
	    ("00" + d.getMinutes()).slice(-2) + ":" + 
	    ("00" + d.getSeconds()).slice(-2)
	);
}